# "dimensions":["continent","robot","country","city","newPage","unpatrolled","namespace","anonymous","language","page","region","user"],
# "metrics":["deleted","added","count","delta"]

druidHost: localhost:8082
dataSources:
  - name: static-wiki
    title: Static Wikipedia
    maxTime: 2013-02-27T00:00:00Z
    timeAttribute: time

    dimensions:
      - name: time
        type: TIME

      - name: namespace

      - name: language

      - name: page

      - name: user

      - name: country

      - name: city

      - name: region

    measures:
      - name: count

      - name: added

      - name: avg_added
        expression: $main.sum($added) / $main.sum($count)

      - name: deleted

      - name: avg_deleted
        expression: $main.sum($deleted) / $main.sum($count)

      - name: delta


  - name: wiki
    title: Wikipedia Edits
    source: wikipedia
    timeAttribute: time

    dimensions:
      - name: time
        type: TIME

      - name: namespace

      - name: language

      - name: page

      - name: user

      - name: country

      - name: city

      - name: region

    measures:
      - name: count

      - name: added

      - name: avg_added
        expression: $main.sum($added) / $main.sum($count)

      - name: deleted

      - name: avg_deleted
        expression: $main.sum($deleted) / $main.sum($count)

      - name: delta

      - name: unique_users
        title: Unique Users
        expression: $main.countDistinct($user_unique)
