# "dimensions":["continent","robot","country","city","newPage","unpatrolled","namespace","anonymous","language","page","region","user"],
# "metrics":["deleted","added","count","delta"]

druidHost: localhost:8082
dataSources:
  - name: static-wiki
    title: Static Wikipedia
    engine: native
    source: assets/data/wikiticker-2015-09-11.json
    maxTime: 2015-09-13T00:00:00Z

    timeAttribute: time

    dimensions:
      - name: time
        type: TIME

      - name: channel

      - name: cityName

      - name: comment

      - name: countryIsoCode

      - name: countryName

      - name: delta

      - name: flags

      - name: isMinor

      - name: isNew

      - name: isRobot

      - name: isUnpatrolled

      - name: metroCode

      - name: namespace

      - name: page

      - name: regionIsoCode

      - name: regionName

      - name: user


    measures:
      - name: count
        expression: $main.count()

      - name: delta

      - name: avg_delta
        expression: $main.sum($delta) / $main.count()


  - name: wiki
    title: Wikipedia Edits
    engine: druid
    source: wikipedia
    timeAttribute: time

    dimensions:
      - name: time
        type: TIME

      - name: namespace

      - name: language

      - name: page

      - name: user

      - name: country

      - name: city

      - name: region

    measures:
      - name: count

      - name: added

      - name: avg_added
        expression: $main.sum($added) / $main.sum($count)

      - name: deleted

      - name: avg_deleted
        expression: $main.sum($deleted) / $main.sum($count)

      - name: delta

      - name: unique_users
        title: Unique Users
        expression: $main.countDistinct($user_unique)
